import { mkdir, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Emits the standard app skeleton for a scored concept.
 *
 * Every app the factory produces starts with the same five loop events already
 * wired, because instrumentation added after launch measures a loop that has
 * already been shaped by guesswork. The scaffold refuses to overwrite an
 * existing directory — regenerating over live code is how work is lost.
 */

export const LOOP_EVENTS = ['signup', 'core_action', 'share', 'share_view', 'referred_signup', 'revenue'];

export function slugify(name) {
  const slug = String(name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  if (!slug) throw new Error(`Cannot derive a directory name from ${JSON.stringify(name)}`);
  return slug;
}

export function planFiles(concept) {
  const slug = slugify(concept.name);
  return {
    slug,
    files: [
      { path: 'README.md', content: readme(concept, slug) },
      { path: 'src/events.mjs', content: eventsModule(concept) },
      { path: 'src/loop.md', content: loopDoc(concept) },
      { path: 'tests/.gitkeep', content: '' }
    ]
  };
}

export async function scaffold(concept, { root = 'apps', force = false } = {}) {
  const { slug, files } = planFiles(concept);
  const target = join(root, slug);

  if (!force && (await exists(target))) {
    throw new Error(`Refusing to scaffold: ${target} already exists. Pass --force only if you intend to overwrite.`);
  }

  for (const file of files) {
    const full = join(target, file.path);
    await mkdir(dirnameOf(full), { recursive: true });
    await writeFile(full, file.content, 'utf8');
  }
  return { target, written: files.map((f) => join(target, f.path)) };
}

function readme(concept, slug) {
  return `# ${concept.name}

Generated by the Viral App Factory Framework from concept \`${concept.id}\` (${slug}).

## Premise
${concept.premise ?? '_Not stated._'}

## Wedge
${concept.wedge ?? '_Not stated._'}

## Primary loop
${concept.primaryLoop ?? '_Not stated._'}

## Monetization
${concept.monetization ?? '_Not stated._'}

## Gate status
This scaffold satisfies G3 instrumentation only once \`src/events.mjs\` is called
from real code paths. Emitting the events from stubs passes the gate and fails
the company.
`;
}

function eventsModule(concept) {
  return `/**
 * Loop instrumentation for ${concept.name}.
 * The six event names below are fixed by the framework so that growth analysis
 * is comparable across every app the factory produces.
 */

export const LOOP_EVENTS = ${JSON.stringify(LOOP_EVENTS, null, 2)};

export function createTracker(sink) {
  return function track(name, props = {}) {
    if (!LOOP_EVENTS.includes(name)) {
      throw new Error(\`Unknown loop event '\${name}'. Extend LOOP_EVENTS deliberately, not incidentally.\`);
    }
    return sink({ name, props, at: new Date().toISOString() });
  };
}
`;
}

function loopDoc(concept) {
  return `# Loop design — ${concept.name}

${concept.primaryLoop ?? '_Loop not stated._'}

| Step | Event | Owner metric |
| --- | --- | --- |
| User arrives | \`signup\` | signups |
| User performs the core action | \`core_action\` | activation rate |
| User shares the artefact | \`share\` | invites per user (i) |
| Someone opens the share | \`share_view\` | reach per share |
| Viewer becomes a user | \`referred_signup\` | invite conversion (c) |
| Money changes hands | \`revenue\` | contribution per user |

K = i x c, measured from these events and no others.
`;
}

function dirnameOf(p) {
  const idx = p.lastIndexOf('/');
  return idx === -1 ? '.' : p.slice(0, idx);
}

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}
